### ISSUE TITLE
Change request for problem "Live Archive/3548.cpp"

### ISSUE THREAD

**Issue by bluemmb** [renzov/Red_Crown#1]
**UPDATE** 
LiveArchieve had problem yesterday and I thought your code is wrong. I am really Sorry about it ...

_Hi. Sorry i am new in github and I didn't know how to suggest changing the code of mentioned problem.

I have used [your nice idea](https://github.com/renzov/Red_Crown/blob/master/Live%20Archive/3548.cpp) for solving the problem. As your code was WA , I was wondering if you are interested in changing it with [this code](http://pastebin.com/cfQbV1mA) ... ? Currently LiveArchieve doesn't work and I had to test it in POJ.

Also after that I coded [another solution](http://pastebin.com/XEQ5zYnK) for it but I am not sure about it's performance!_

**Comment by renzov** [comment]
Hi,

I have submitted my code to the POJ judge and resubmitted to the Live Archive and it gave me AC.
Excuse me, but I don't have a reason to change it.
